# matsushibadenki/snn/configs/base_config.yaml
# プロジェクトの基本設定ファイル

# 共通設定
seed: 42
# ◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️↓修正開始◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️
# device: "cuda" # NVIDIA GPUがない環境（Macなど）ではエラーになるため、"mps"または"cpu"を推奨
device: "mps"
# ◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️↑修正終わり◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️

# データ設定
data:
  # データパスはコマンドライン引数で上書きすることを想定
  path: "data/wikitext-103_train.jsonl"
  format: "simple_text"
  split_ratio: 0.1 # 検証用データの割合

# モデルアーキテクチャ設定
model:
  path: "breakthrough_snn_model.pth"
  d_model: 256
  d_state: 128
  num_layers: 8
  time_steps: 20
  n_head: 4 # for SpikingTemporalAttention

# 学習パラメータ設定
training:
  type: "standard" # "standard", "distributed", "distillation" から選択
  epochs: 10
  batch_size: 16 # 分散学習時はGPUあたりのサイズ
  learning_rate: 0.0005
  use_scheduler: true
  grad_clip_norm: 1.0

  # 損失関数の重み
  loss:
    ce_weight: 1.0
    spike_reg_weight: 0.01

  # 蒸留学습設定 (training.typeが 'distillation' の場合に参照)
  distillation:
    teacher_model: "gpt2"
    loss:
      ce_weight: 0.3
      distill_weight: 0.7
      spike_reg_weight: 0.01
      temperature: 2.0

  # ログ出力間隔
  log_interval: 1

# 推論/アプリ設定
# ◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️↓修正開始◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️
inference:
  device: "mps"
  max_len: 50
# ◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️↑修正終わり◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️

# Gradioアプリ設定
app:
  server_name: "0.0.0.0"
  server_port: 7860
